---
ID: "f740f299-866f-4f29-a99e-533e604c6977"
Parent: "e828ed37-5f08-4466-a124-135f83fb118e"
Template: "e828ed37-5f08-4466-a124-135f83fb118e"
Path: /sitecore/templates/Feature/Events/Event/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230510T160928Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jeff.rondeau@merkle.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jeff.rondeau@merkle.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "57eb5b09-ae8a-451a-9402-4cb381a1295c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jeff.rondeau@merkle.com
    - ID: "c5700f96-7702-4457-bd9b-0f0d52e99a02"
      Hint: EventName
      Value: $name
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230510T160935Z
